version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: noble6/cryptotracker_backend:latest
    restart: always
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
    depends_on:
      - db
    env_file:
      - ./.env

#  frontend:
#    image: noble6/cryptotracker_frontend:latest
#    volumes:
#      - frontend_value:/app/build/
#    depends_on:
#      - db

  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend_value:/usr/share/nginx/html/
      - static_value:/code/static/
      - media_value:/code/media/
    depends_on:
      - backend
      #- frontend

volumes:
  postgres_data:
  static_value:
  media_value:
  frontend_value: